### PR TITLE
Update to app dir

### PR DESCRIPTION
**Pull request by entity**
Hi all,

This pull request migrates the codebase to support the new `app` directory within Next.js v13. This new directory allows components to become server-side rendered and also tidies up some options.

In addition, it fixes the flicker bug that will show the dashboard (or any auth endpoint) for a split second.

The only thing not implemented with this directive are the header props, as it doesn't seem possible with the multi-shared layout. However I am open to any feedback/commits to it if anyone knows.

Thanks

### CODE REVIEW

**Comment by driesvints** [comment]
@heychazza can you remove the yarn.lock (which we don't use ourselves).

**Comment by entity** [comment]
> @heychazza can you remove the yarn.lock (which we don't use ourselves).

Done! :)

I've also fixed the "flash" issue that happened in this template, where users could see the dashboard for a split second before the redirect kicks in.

**Comment by taylorotwell** [comment]
Will wait for follow up on the header props.

**Comment by ammar-madni** [comment]
@heychazza @taylorotwell  As far as I know it's not possible to pass props to layout components from the children with the new app router. Could we not just keep it simple and create a Header component?
```jsx
const Header = ({ children }) => {
    return (
        <header className="bg-white shadow">
            <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                {children}
            </div>
        </header>
    )
}

export default Header
```

Then use this component in each page, for example:
```jsx
import Header from '@/components/Header'

const Dashboard = () => {
    return (
        <>
            <Header>
                <h2 className="font-semibold text-xl text-gray-800 leading-tight">
                    Dashboard
                </h2>
            </Header>
            <main>
                <div className="py-12">
                    <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                        <div className="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                            <div className="p-6 bg-white border-b border-gray-200">
                                You're logged in!
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}

export default Dashboard
```

The layout.js component will also need to be updated:
```jsx
'use client';

import Navigation from '@/components/Navigation';
import { useAuth } from '@/hooks/auth';

export default function AuthLayout({ children }) {
    const { user } = useAuth({ middleware: 'auth' })

    if (typeof user === "undefined") {
        return null;
    }

    return (
        <div className="min-h-screen bg-gray-100">
            <Navigation />
            {children}
        </div>
    )
}
```

**Comment by Silomalo** [comment]
@heychazza @taylorotwell @ammar-madni  With the new implementation getting: Error: Request failed with status code 404 on login and register! how can that be solved ?

**Comment by Silomalo** [comment]
@heychazza @taylorotwell @ammar-madni  how can we allow users to visit certain pages based on roles? at the same time redirect users back to if they try to access restricted resource/page

**Comment by entity** [comment]
> @heychazza @taylorotwell @ammar-madni how can we allow users to visit certain pages based on roles? at the same time redirect users back to if they try to access restricted resource/page

I’d love to help, but this question isn’t relevant to the PR. You’d be best to ask in the Discord.

**Comment by johnymanuelli** [comment]
Any update on upgrading this repo to use Next 13 ? Thanks

**Comment by entity** [comment]
> Any update on upgrading this repo to use Next 13 ? Thanks

The repo is already Next v13, it’s just using the pages router instead. This PR changes to the app router

**Comment by liamseys** [comment]
@driesvints when do you have time to handle this PR? Would love to see this merged.

**Comment by driesvints** [comment]
@liamseys I don't review PRs or handle the breeze-next repo sorry. Taylor doesn't see draft PRs so if you need feedback or a review please mark this as ready.

**Comment by driesvints** [comment]
@heychazza are you still working on this one?

**Comment by entity** [comment]
> @heychazza are you still working on this one?

Yes, just been busy - happy for you to P.R. if you wanted to finalise the headers

**Comment by priteshloke** [comment]
Using same auth hook with new nextjs 13 structure https://github.com/priteshloke/breeze-next-13

**Comment by Deniz073** [comment]
Why has this pr been closed? Any updates on whether this repo will be updated to use the app dir?

**Comment by Silomalo** [comment]
@Deniz073 I have used it in production using a app dir, works fine and also redirects well, just include a role column in your user table and make user of the middleware's to guide your redirection on each page load.

**Comment by vipertecpro** [comment]
Hello everyone, if anyone has time, can you please take a look into this.
https://github.com/vipertecpro/nextjs-app-for-laravel-apis
I am using app Dir, i don't know if it is correct or not.

**Pull request closed without merging**
